// <auto-generated />
using System;
using BackendPortalAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendPortalAPI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618173048_AddStatusNote")]
    partial class AddStatusNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendPortalAPI.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Congregation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TblUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Congregation = "Dubai (Main)",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "benjamin@csitamilparishdubai.com",
                            IsDeleted = false,
                            Name = "Rev. Benjamin",
                            Role = "Diocese Admin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Congregation = "Dubai (Main)",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "presbyter@csitamilparishdubai.com",
                            IsDeleted = false,
                            Name = "Rev. S. Daniel",
                            Role = "Parish Presbyter",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            Congregation = "Fujairah",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "moderator@csitamilparishdubai.com",
                            IsDeleted = false,
                            Name = "Sis. Mary J.",
                            Role = "Moderator",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            Congregation = "Dubai (Main)",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "office@csitamilparishdubai.com",
                            IsDeleted = false,
                            Name = "Office Desk",
                            Role = "Office Staff",
                            Status = "Invited"
                        });
                });

            modelBuilder.Entity("BackendPortalAPI.Domain.Entities.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromMobile")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ToName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ToProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToReferenceId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ToProfileId");

                    b.ToTable("TblInterests", (string)null);
                });

            modelBuilder.Entity("BackendPortalAPI.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Congregation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MembershipNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MembershipNo")
                        .IsUnique();

                    b.ToTable("TblMembers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            Congregation = "Dubai",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MembershipNo = "CSI-DXB-1001",
                            Name = "Mr. & Mrs. Rajesh Daniel"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            Congregation = "Dubai",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MembershipNo = "CSI-DXB-1002",
                            Name = "Mr. & Mrs. Samuel John"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            Congregation = "Fujairah",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MembershipNo = "CSI-FUJ-2001",
                            Name = "Mr. & Mrs. Christopher"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            Congregation = "Ras Al Khaimah",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MembershipNo = "CSI-RAK-3001",
                            Name = "Mr. & Mrs. Wilson"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            Congregation = "Dubai",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            IsDeleted = false,
                            MembershipNo = "CSI-DXB-9999",
                            Name = "Lapsed Membership"
                        });
                });

            modelBuilder.Entity("BackendPortalAPI.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AboutFaith")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Congregation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Denomination")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("FatherOccupation")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Height")
                        .HasColumnType("text");

                    b.Property<string>("HomeParish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LookingFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MainPhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MembershipNo")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MotherOccupation")
                        .HasColumnType("text");

                    b.Property<string>("MotherTongue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.ToTable("TblProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            AboutFaith = "Active in church fellowship and ministry.",
                            City = "Dubai, UAE",
                            Congregation = "Dubai",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedFor = "Self",
                            DateOfBirth = new DateOnly(2000, 6, 15),
                            Denomination = "CSI",
                            Education = "Master's (M.Sc Nursing)",
                            FullName = "Abinaya R.",
                            Gender = "Female",
                            Height = "5'4\"",
                            HomeParish = "CSI Tamil Parish, Dubai",
                            IsDeleted = false,
                            LookingFor = "Groom",
                            MaritalStatus = "Never married",
                            Mobile = "+971 50 000 0000",
                            MotherTongue = "Tamil",
                            Profession = "Staff Nurse",
                            ReferenceId = "CSI1042",
                            Status = "Verified"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            AboutFaith = "Active in church fellowship and ministry.",
                            City = "Fujairah, UAE",
                            Congregation = "Fujairah",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedFor = "Self",
                            DateOfBirth = new DateOnly(1997, 6, 15),
                            Denomination = "CSI",
                            Education = "Bachelor's (B.E)",
                            FullName = "Daniel J.",
                            Gender = "Male",
                            Height = "5'10\"",
                            HomeParish = "CSI Tamil Congregation, Fujairah",
                            IsDeleted = false,
                            LookingFor = "Bride",
                            MaritalStatus = "Never married",
                            Mobile = "+971 50 000 0000",
                            MotherTongue = "Tamil",
                            Profession = "Software Engineer",
                            ReferenceId = "CSI1043",
                            Status = "Verified"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            AboutFaith = "Active in church fellowship and ministry.",
                            City = "Dubai, UAE",
                            Congregation = "Dubai",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedFor = "Self",
                            DateOfBirth = new DateOnly(2002, 6, 15),
                            Denomination = "Pentecostal",
                            Education = "Bachelor's (B.Com)",
                            FullName = "Sharon P.",
                            Gender = "Female",
                            Height = "5'2\"",
                            HomeParish = "Bethel AG Church, Dubai",
                            IsDeleted = false,
                            LookingFor = "Groom",
                            MaritalStatus = "Never married",
                            Mobile = "+971 50 000 0000",
                            MotherTongue = "Tamil",
                            Profession = "Accountant",
                            ReferenceId = "CSI1044",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            AboutFaith = "Active in church fellowship and ministry.",
                            City = "Ras Al Khaimah, UAE",
                            Congregation = "Ras Al Khaimah",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedFor = "Self",
                            DateOfBirth = new DateOnly(1995, 6, 15),
                            Denomination = "CSI",
                            Education = "Doctorate (PhD)",
                            FullName = "Immanuel S.",
                            Gender = "Male",
                            Height = "6'0\"",
                            HomeParish = "CSI Tamil Congregation, Ras Al Khaimah",
                            IsDeleted = false,
                            LookingFor = "Bride",
                            MaritalStatus = "Never married",
                            Mobile = "+971 50 000 0000",
                            MotherTongue = "Tamil",
                            Profession = "College Lecturer",
                            ReferenceId = "CSI1045",
                            Status = "Verified"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            AboutFaith = "Active in church fellowship and ministry.",
                            City = "London, UK",
                            Congregation = "Other",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedFor = "Self",
                            DateOfBirth = new DateOnly(1998, 6, 15),
                            Denomination = "CSI",
                            Education = "Master's (M.A)",
                            FullName = "Rebecca A.",
                            Gender = "Female",
                            Height = "5'5\"",
                            HomeParish = "CSI Tamil Fellowship, London",
                            IsDeleted = false,
                            LookingFor = "Groom",
                            MaritalStatus = "Never married",
                            Mobile = "+971 50 000 0000",
                            MotherTongue = "Tamil",
                            Profession = "School Teacher",
                            ReferenceId = "CSI1046",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            AboutFaith = "Active in church fellowship and ministry.",
                            City = "Chennai, India",
                            Congregation = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedFor = "Self",
                            DateOfBirth = new DateOnly(1999, 6, 15),
                            Denomination = "Lutheran",
                            Education = "Bachelor's (B.Sc)",
                            FullName = "Joel V.",
                            Gender = "Male",
                            Height = "5'8\"",
                            HomeParish = "TELC Church, Chennai",
                            IsDeleted = false,
                            LookingFor = "Bride",
                            MaritalStatus = "Never married",
                            Mobile = "+971 50 000 0000",
                            MotherTongue = "Tamil",
                            Profession = "Lab Technician",
                            ReferenceId = "CSI1047",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("BackendPortalAPI.Domain.Entities.Shortlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberId", "ProfileId")
                        .IsUnique();

                    b.ToTable("TblShortlists", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
